[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["https://software.repos.intel.com/python/conda/", "conda-forge"]
description = "Add a short description here"
name = "llvm-sycl"
platforms = ["linux-64"]
version = "20.0.0"

[target.linux-64.dependencies]
cuda = ">=12.6.2,<13"
pkg-config = ">=0.29.2,<0.30"
pkgconfig = ">=1.5.5,<2"
sysroot_linux-64 = ">=2.34"
intel-opencl-rt = ">=2025.0.0,<2026"
intel-fortran-rt = ">=2025.0.0,<2026"
intel-opencl-fpga-emu-rt = ">=2025.0.0,<2026"
clinfo = ">=3.0.21.2.21,<4"
tbb-devel = ">=2022.0.0,<2023"
libxml2 = ">=2.13.5,<3"
zlib = ">=1.3.1,<2"

[target.linux-64.build-dependencies]
cmake = ">=3.30.5,<4"
python = ">=3.12.5,<3.13"
pkgconfig = ">=1.5.5,<2"
pkg-config = ">=0.29.2,<0.30"
cxx-compiler = ">=1.8.0,<2"
c-compiler = ">=1.8.0,<2"
git = ">=2.47.0,<3"
ninja = ">=1.12.1,<2"
wget = ">=1.21.4,<2"
ccache = ">=4.10.1,<5"
lld = ">=19.1.3,<20"

[target.linux-64.host-dependencies]
sysroot_linux-64 = ">=2.34"
ocl-icd = ">=2.3.2,<3"
cuda = ">=12.6.2,<13"
zstd-static = ">=1.5.6,<2"
libxml2 = ">=2.13.5,<3"
zlib = ">=1.3.1,<2"

[target.linux-64.activation]
scripts = ["../../activation/linux.sh", "../../activation/dpcpp-build.sh"]

[target.linux-64.tasks]
configure = { cmd = "bash scripts/configure.sh" }
install = { cmd = "bash scripts/install.sh" }
