context:
  name: llvm-sycl
  version: 20.0.0
  inherited-env-vars:
    - SYCL_PROJECT_ROOT

package:
  name: ${{ name|lower }}
  version: ${{ version }}

build:
  script:
    interpreter: bash
    content: |
      bash $SYCL_PROJECT_ROOT/recipes/scripts/configure.sh 
      bash $SYCL_PROJECT_ROOT/recipes/scripts/build.sh 
      bash $SYCL_PROJECT_ROOT/recipes/scripts/install.sh

requirements:
  host:
    - ocl-icd >=2.3.2,<3
    - cuda >=12.6.2,<13
    - sysroot_linux-64 >=2.34
  build:
    - cmake >=3.30.5,<4
    - pkg-config >=0.29.2,<0.30
    - pkgconfig >=1.5.5,<2
    - cxx-compiler >=1.8.0,<2
    - c-compiler >=1.8.0,<2
    - git >=2.47.0,<3
    - ninja >=1.12.1,<2
    - wget >=1.21.4,<2
    - ccache >=4.10.1,<5
    - lld >=19.1.3,<20
  run:
    - cuda >=12.6.2,<13
    - sysroot_linux-64 >=2.34
    - intel-opencl-rt >=2025.0.0,<2026
    - intel-fortran-rt >=2025.0.0,<2026
    - intel-opencl-fpga-emu-rt >=2025.0.0,<2026
    - clinfo >=3.0.21.2.21,<4
