export DPCPP_HOME=$PIXI_PROJECT_ROOT
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
export CUDA_LIB_PATH="$CONDA_PREFIX/targets/x86_64-linux/lib/stubs"
export CXXFLAGS=$CONDA_BACKUP_CXXFLAGS
export CFLAGS=$CONDA_BACKUP_CFLAGS
export LDFLAGS=$CONDA_BACKUP_LDFLAGS
export CMAKE_ARGS=$CONDA_BACKUP_CMAKE_ARGS
export CPPFLAGS=$CONDA_BACKUP_CXXFLAGS
export CXX=$CONDA_BACKUP_CXX
export CC=$CONDA_BACKUP_CC
export CXX_COMPILER=$CXX
export C_COMPILER=$CC

if [ -z "$SYCL_INSTALL_PREFIX" ]; then
  export SYCL_INSTALL_PREFIX="$PIXI_PROJECT_ROOT/intel/oneapi"
fi

export CMAKE_PREFIX_PATH="$CONDA_BACKUP_CMAKE_PREFIX_PATH:$SYCL_INSTALL_PREFIX/tbb/oneapi-tbb-2021.12.0"
export CMAKE_SYSROOT=$CONDA_BUILD_SYSROOT

# cpp_incl_path="$(find "$CONDA_PREFIX" -wholename "*/include/c++" -type d)"
# export CMAKE_INCLUDE_PATH="$cpp_incl_path"
