[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["https://software.repos.intel.com/python/conda", "conda-forge"]
description = "Add a short description here"
name = "build-intel-sycl"
platforms = ["linux-64"]
version = "0.1.0"

# Default system requirements for Linux
[system-requirements]
linux = "4.18"
libc = { family = "glibc", version = "2.28" }

[feature.sycl-build.tasks]
setup = "bash ./recipes/dpcpp/scripts/setup.sh"
clone = { cmd = "./recipes/dpcpp/scripts/clone.sh", depends-on = ["setup"] }
intel-runtimes = { cmd = "python ./recipes/dpcpp/scripts/download_intel_runtimes.py", depends-on = [
  "clone",
] }
configure = { cmd = "./recipes/dpcpp/scripts/configure.sh", depends-on = [
  "intel-runtimes",
] }
build = { cmd = "./recipes/dpcpp/scripts/build.sh", depends-on = ["configure"] }
install = { cmd = "./recipes/dpcpp/scripts/install.sh", depends-on = ["build"] }

[feature.onemkl-build.tasks]
clone = { cmd = "./recipes/onemkl/scripts/clone_mkl.sh", depends-on = [
  "install",
] }
configure = { cmd = "./recipes/onemkl/scripts/configure_mkl.sh", depends-on = [
  "clone",
] }
build = { cmd = "./recipes/onemkl/scripts/build_mkl.sh", depends-on = [
  "configure",
] }
install = { cmd = "./recipes/onemkl/scripts/install_mkl.sh", depends-on = [
  "build",
] }

[feature.run.activation]
scripts = ["recipes/dpcpp/env.sh", "recipes/onemkl/env.sh"]

[feature.onemkl-build.activation]
scripts = ["recipes/onemkl/env.sh"]

[feature.build.activation]
scripts = ["recipes/dpcpp/env.sh"]

[feature.build.dependencies]
cmake = ">=3.30.5,<4"
python = ">=3.11.9,<4"
ninja = ">=1.12.1,<2"
ocl-icd-system = ">=1.0.0,<2"
ocl-icd = ">=2.3.2,<3"
wget = ">=1.21.4,<2"
git = ">=2.47.0,<3"
ccache = ">=4.10.1,<5"
lld = ">=19.1.2,<20"
cxx-compiler = ">=1.8.0,<2"
c-compiler = ">=1.8.0,<2"
libstdcxx-devel_linux-64 = ">=13.3.0,<14"
pkg-config = ">=0.29.2,<0.30"
spirv-headers = ">=1.3.296.0,<2"
spirv-tools = ">=2024.3,<2025"
vulkan-tools = ">=1.3.290,<2"
vulkan-headers = ">=1.3.231.1,<2"
libvulkan-loader = ">=1.3.290.0,<2"
mkl-devel-dpcpp = ">=2024.2.2,<2025"
llvm = ">=19.1.2,<20"
cuda = ">=12.6.2,<13"
sysroot_linux-64 = ">=2.28"

[feature.run.dependencies]
libstdcxx-devel_linux-64 = ">=13.3.0,<14"
pkg-config = ">=0.29.2,<0.30"
spirv-headers = ">=1.3.296.0,<2"
spirv-tools = ">=2024.3,<2025"
vulkan-tools = ">=1.3.290,<2"
vulkan-headers = ">=1.3.231.1,<2"
libvulkan-loader = ">=1.3.290.0,<2"
llvm = ">=19.1.2,<20"
cuda = ">=12.6.2,<13"
sysroot_linux-64 = ">=2.28"
ocl-icd = ">=2.3.2,<3"
clinfo = ">=3.0.21.2.21,<4"

[feature.update-deps.dependencies]
python = ">=3.11.9,<4"
tomlkit = ">=0.13.2,<0.14"

[environments]
onemkl-build = ["build", "onemkl-build"]
sycl-build = ["build", "sycl-build"]
run = ["run"]
update-deps = ["update-deps"]
