[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["https://software.repos.intel.com/python/conda/", "conda-forge"]
description = "Add a short description here"
name = "onemkl"
# platforms = ["win-64", "linux-64"]
platforms = ["linux-64"]

# Common among all toolchains
[dependencies]
python = ">=3.12.5,<4"
cmake = ">=3.30.5,<4"
ninja = ">=1.12.1,<2"
git = ">=2.47.0,<3"
ccache = ">=4.10.1,<5"
pkg-config = ">=0.29.2,<0.30"
pkgconfig = ">=1.5.5,<2"

[target.linux-64.dependencies]
sysroot_linux-64 = ">=2.28"
ocl-icd = ">=2.3.2,<3"
ocl-icd-system = ">=1.0.0,<2"
clinfo = ">=3.0.21.2.21,<4"
wget = ">=1.21.4,<2"
cuda = ">=12.6.2,<13"

[target.linux-64.activation]
scripts = ["activation/linux.sh", "activation/dpcpp.sh"]

[feature.ocl-extras.dependencies]
intel-opencl-rt = ">=2024.2.1,<2025"
intel-fortran-rt = ">=2024.2.1,<2025"
intel-opencl-fpga-emu-rt = ">=2024.2.1,<2025"


[tasks]
link-presets = { cmd = "ln -sf $PIXI_PROJECT_ROOT/CMakePresets.json $PIXI_PROJECT_ROOT/onemkl/CMakePresets.json", outputs = [
  "onemkl/CMakePresets.json",
] }
configure = { cmd = "cmake onemkl --preset onemkl-build-linux", depends-on = [
  "link-presets",
] }
build = { cmd = "cmake --build onemkl/build", depends-on = ["configure"] }
install = { cmd = "cmake --install onemkl/build", depends-on = ["build"] }
