set(CMAKE_C_COMPILER "$ENV{CC}")
set(CMAKE_CXX_COMPILER "$ENV{CXX}")

if(NOT "$ENV{NO_INSTALL_RPATH}" STREQUAL "1")
  if("$ENV{INSTALL_RPATHS}" STREQUAL "")
    set(CMAKE_INSTALL_RPATH
        "\$ORIGIN;\$ORIGIN/../lib;\$ORIGIN/../lib64;\$ORIGIN/../targets/x86_64-linux/lib/stubs"
    )
  else()
    set(CMAKE_INSTALL_RPATH "$ENV{INSTALL_RPATHS}")
  endif()
  set(CMAKE_SKIP_RPATH
      FALSE
      CACHE BOOL "" FORCE)
  set(CMAKE_SKIP_INSTALL_RPATH
      FALSE
      CACHE BOOL "" FORCE)
  set(CMAKE_SKIP_BUILD_RPATH
      FALSE
      CACHE BOOL "" FORCE)
endif()

# location of the target environment
set(CMAKE_FIND_ROOT_PATH "$ENV{PREFIX}" "$ENV{CONDA_BUILD_SYSROOT}")

set(CMAKE_SYSROOT "$ENV{CONDA_BUILD_SYSROOT}")

set(CUDA_TOOLKIT_ROOT_DIR "$ENV{CUDA_ROOT}")

if(NOT "$ENV{CHAINLOAD_TOOLCHAIN_FILE}" STREQUAL ""
   AND NOT CHAINLOAD_TOOLCHAIN_FILE)
  set(CHAINLOAD_TOOLCHAIN_FILE "$ENV{CHAINLOAD_TOOLCHAIN_FILE}")
endif()

if(CHAINLOAD_TOOLCHAIN_FILE)
  include("${CHAINLOAD_TOOLCHAIN_FILE}")
endif()
