set(CMAKE_C_COMPILER "$ENV{CC}")
set(CMAKE_CXX_COMPILER "$ENV{CXX}")

# location of the target environment
set(CMAKE_FIND_ROOT_PATH "$ENV{PREFIX}" "$ENV{CONDA_BUILD_SYSROOT}")

set(CMAKE_SYSROOT "$ENV{CONDA_BUILD_SYSROOT}")

set(CUDA_TOOLKIT_ROOT_DIR "$ENV{CUDA_ROOT}")

if(NOT "$ENV{CHAINLOAD_TOOLCHAIN_FILE}" STREQUAL ""
   AND NOT CHAINLOAD_TOOLCHAIN_FILE)
  set(CHAINLOAD_TOOLCHAIN_FILE "$ENV{CHAINLOAD_TOOLCHAIN_FILE}")
endif()

if(CHAINLOAD_TOOLCHAIN_FILE)
  include("${CHAINLOAD_TOOLCHAIN_FILE}")
endif()
