#!/bin/bash

project_dir=
if [ -z "$1" ]; then
  project_dir="$PWD"
else
  project_dir="$1"
fi

pixi init "$project_dir"

cd "$project_dir" || exit

pixi add cuda-libraries-dev cuda-nvcc cuda-nvtx cuda-cupti ocl-icd ocl-icd-system

oneapi_dir=$(cwd=$PWD && cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd && cd "$cwd" || exit)/..

pixi run "ln -sf $oneapi_dir/etc/OpenCL/vendors/* $CONDA_PREFIX/etc/OpenCL/vendors"

echo "source $oneapi_dir/setvars.sh" | tee $project_dir/env.sh

echo "\n[activation]" | tee -a $project_dir/pixi.toml
echo "scripts = [ \"env.sh\" ]" | tee -a $project_dir/pixi.toml
