#!/bin/bash

project_dir=
if [ -z "$1" ]; then
  project_dir="$PWD"
else
  project_dir="$1"
fi

pixi init "$project_dir"

cd "$project_dir" || exit

pixi add cuda-libraries-dev cuda-nvcc cuda-nvtx cuda-cupti ocl-icd ocl-icd-system python
pixi add --pypi cmake-init

oneapi_dir=$(cwd=$PWD && cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd && cd "$cwd" || exit)/..

ln -sf $oneapi_dir/etc/OpenCL/vendors/* $PWD/.pixi/envs/default/etc/OpenCL/vendors
pixi run cmake-init

echo "source $oneapi_dir/setvars.sh" >env.sh

printf '\n[activation]\n' >>pixi.toml
echo "scripts = [ \"env.sh\" ]" >>pixi.toml
